# Site settings
title: Taunton Lab Website
email: jack.taunton@ucsf.edu
description: "Laboratory of Jack Taunton @ UCSF"
baseurl: ""
url: "http://tauntonlab.ucsf.edu"

# Build settings
markdown: kramdown
permalink: pretty
